#web:
 # uploadPath: /root/apache-tomcat-8.5.38/webapps/images/avatar

#    uploadPath: E:\api\testImage
#    upload-path: E:\api\testImage
#    questionImagePath: E:\api\testImage
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/info_processing?serverTimezone=GMT
    username: root
    password: 123

  jpa:
    database: MySQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
    multipart:
      max-file-size: -1
      max-request-size: -1
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

endpoints:
  actuator:
    enabled: true
    sensitive: false
logging:
  path: /Users/chenjie/IdeaProjects/igarden/log
  file: base.log
mybatis:
  typeAliasesPackage: cn.edu.bjfu.igarden.dao.entity
  mapperLocations: classpath:mapper/*.xml
server:
  undertow:
    worker-threads: 400
    io-threads: 100
    buffer-size: 102400
    direct-buffers: true
weixinconfig:
  weixinappID: wxbcf87ba1e79378d5
  weixinappSecret: 48bf689ba9b48d94837f688779059395
  weixinappID1: wxc36348eb1a6bca49
  weixinappSecret1: 8129f062f625836f4b7f8b4140502e18